import type { PageDocument } from '../editor/document/types';

export const executiveDemoDocument = {
  version: 1,
  id: 'executive-demo',
  name: 'Executive Overview',
  rootNodeId: 'root',
  nodes: {
    root: {
      id: 'root',
      type: 'mui.container',
      children: ['page-stack'],
      props: { maxWidth: 'lg' },
      style: {
        sx: {
          py: { xs: 3, md: 5, lg: 7 },
          px: { xs: 2, sm: 3, lg: 4 },
        },
      },
    },
    'page-stack': {
      id: 'page-stack',
      type: 'mui.stack',
      parentId: 'root',
      children: ['header', 'kpis', 'portfolio-heading', 'portfolio-card'],
      props: { spacing: { xs: 3, md: 4 } },
      style: {},
    },
    header: {
      id: 'header',
      type: 'mui.stack',
      parentId: 'page-stack',
      children: ['eyebrow', 'title', 'subtitle'],
      props: { spacing: 0.75 },
      style: {},
    },
    eyebrow: {
      id: 'eyebrow',
      type: 'mui.typography',
      parentId: 'header',
      children: [],
      props: {
        content: 'EXECUTIVE DASHBOARD',
        variant: 'overline',
        color: 'primary.main',
      },
      style: { sx: { fontWeight: 800, letterSpacing: '0.12em' } },
    },
    title: {
      id: 'title',
      type: 'mui.typography',
      parentId: 'header',
      children: [],
      props: { content: 'Executive Overview', variant: 'h3' },
      style: { sx: { fontSize: { xs: '2rem', md: '2.75rem' } } },
    },
    subtitle: {
      id: 'subtitle',
      type: 'mui.typography',
      parentId: 'header',
      children: [],
      props: {
        content: "A concise view of today's business performance.",
        variant: 'body1',
        color: 'text.secondary',
      },
      style: {},
    },
    kpis: {
      id: 'kpis',
      type: 'mui.stack',
      parentId: 'page-stack',
      children: ['revenue-card', 'margin-card', 'inventory-card'],
      props: {
        direction: { xs: 'column', md: 'row' },
        spacing: { xs: 1.5, md: 2.5 },
      },
      style: { sx: { alignItems: 'stretch' } },
    },
    'revenue-card': {
      id: 'revenue-card',
      type: 'mui.card',
      parentId: 'kpis',
      children: ['revenue-content'],
      props: {},
      style: { sx: { flex: 1 } },
    },
    'revenue-content': {
      id: 'revenue-content',
      type: 'mui.cardContent',
      parentId: 'revenue-card',
      children: ['revenue-label', 'revenue-value', 'revenue-change'],
      props: {},
      style: { sx: { p: 3, '&:last-child': { pb: 3 } } },
    },
    'revenue-label': {
      id: 'revenue-label',
      type: 'mui.typography',
      parentId: 'revenue-content',
      children: [],
      props: { content: 'Revenue', color: 'text.secondary' },
      style: { sx: { mb: 1.25, fontWeight: 600 } },
    },
    'revenue-value': {
      id: 'revenue-value',
      type: 'mui.typography',
      parentId: 'revenue-content',
      children: [],
      props: { content: '$4.28M', variant: 'h4' },
      style: { sx: { mb: 1 } },
    },
    'revenue-change': {
      id: 'revenue-change',
      type: 'mui.typography',
      parentId: 'revenue-content',
      children: [],
      props: { content: '+8.4%', color: 'secondary.main' },
      style: { sx: { fontWeight: 750 } },
    },
    'margin-card': {
      id: 'margin-card',
      type: 'mui.card',
      parentId: 'kpis',
      children: ['margin-content'],
      props: {},
      style: { sx: { flex: 1 } },
    },
    'margin-content': {
      id: 'margin-content',
      type: 'mui.cardContent',
      parentId: 'margin-card',
      children: ['margin-label', 'margin-value', 'margin-change'],
      props: {},
      style: { sx: { p: 3, '&:last-child': { pb: 3 } } },
    },
    'margin-label': {
      id: 'margin-label',
      type: 'mui.typography',
      parentId: 'margin-content',
      children: [],
      props: { content: 'Margin', color: 'text.secondary' },
      style: { sx: { mb: 1.25, fontWeight: 600 } },
    },
    'margin-value': {
      id: 'margin-value',
      type: 'mui.typography',
      parentId: 'margin-content',
      children: [],
      props: { content: '31.4%', variant: 'h4' },
      style: { sx: { mb: 1 } },
    },
    'margin-change': {
      id: 'margin-change',
      type: 'mui.typography',
      parentId: 'margin-content',
      children: [],
      props: { content: '+2.1%', color: 'secondary.main' },
      style: { sx: { fontWeight: 750 } },
    },
    'inventory-card': {
      id: 'inventory-card',
      type: 'mui.card',
      parentId: 'kpis',
      children: ['inventory-content'],
      props: {},
      style: { sx: { flex: 1 } },
    },
    'inventory-content': {
      id: 'inventory-content',
      type: 'mui.cardContent',
      parentId: 'inventory-card',
      children: ['inventory-label', 'inventory-value', 'inventory-change'],
      props: {},
      style: { sx: { p: 3, '&:last-child': { pb: 3 } } },
    },
    'inventory-label': {
      id: 'inventory-label',
      type: 'mui.typography',
      parentId: 'inventory-content',
      children: [],
      props: { content: 'Inventory', color: 'text.secondary' },
      style: { sx: { mb: 1.25, fontWeight: 600 } },
    },
    'inventory-value': {
      id: 'inventory-value',
      type: 'mui.typography',
      parentId: 'inventory-content',
      children: [],
      props: { content: '12,840', variant: 'h4' },
      style: { sx: { mb: 1 } },
    },
    'inventory-change': {
      id: 'inventory-change',
      type: 'mui.typography',
      parentId: 'inventory-content',
      children: [],
      props: { content: '-4.2%', color: 'error.main' },
      style: { sx: { fontWeight: 750 } },
    },
    'portfolio-heading': {
      id: 'portfolio-heading',
      type: 'mui.typography',
      parentId: 'page-stack',
      children: [],
      props: { content: 'Portfolio Overview', variant: 'h5' },
      style: { sx: { mt: { xs: 1, md: 2 }, fontWeight: 700 } },
    },
    'portfolio-card': {
      id: 'portfolio-card',
      type: 'mui.paper',
      parentId: 'page-stack',
      children: ['portfolio-stack'],
      props: {},
      style: {
        sx: {
          border: '1px solid',
          borderColor: 'divider',
          borderRadius: 2.5,
          overflow: 'hidden',
        },
      },
    },
    'portfolio-stack': {
      id: 'portfolio-stack',
      type: 'mui.stack',
      parentId: 'portfolio-card',
      children: ['portfolio-top', 'portfolio-divider', 'portfolio-actions'],
      props: { spacing: 0 },
      style: {},
    },
    'portfolio-top': {
      id: 'portfolio-top',
      type: 'mui.stack',
      parentId: 'portfolio-stack',
      children: ['portfolio-title', 'portfolio-copy'],
      props: { spacing: 1 },
      style: { sx: { p: { xs: 2.5, md: 3 } } },
    },
    'portfolio-title': {
      id: 'portfolio-title',
      type: 'mui.typography',
      parentId: 'portfolio-top',
      children: [],
      props: { content: 'Portfolio status', variant: 'h6' },
      style: {},
    },
    'portfolio-copy': {
      id: 'portfolio-copy',
      type: 'mui.typography',
      parentId: 'portfolio-top',
      children: [],
      props: {
        content: 'Current portfolio performance is stable.',
        color: 'text.secondary',
      },
      style: {},
    },
    'portfolio-divider': {
      id: 'portfolio-divider',
      type: 'mui.divider',
      parentId: 'portfolio-stack',
      children: [],
      props: {},
      style: {},
    },
    'portfolio-actions': {
      id: 'portfolio-actions',
      type: 'mui.box',
      parentId: 'portfolio-stack',
      children: ['view-details'],
      props: {},
      style: { sx: { px: { xs: 2.5, md: 3 }, py: 2, textAlign: 'right' } },
    },
    'view-details': {
      id: 'view-details',
      type: 'mui.button',
      parentId: 'portfolio-actions',
      children: [],
      props: {
        content: 'View details',
        variant: 'contained',
        endIcon: 'arrowForward',
      },
      style: {},
    },
  },
} satisfies PageDocument;
